server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/users
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notificationServiceCircuitBreaker
                    fallbackUri: forward:/fallback/notifications

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        base-config: default
      notificationServiceCircuitBreaker:
        base-config: default
